/* This file is automatically generated by Lemon from input grammar
** source file "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#include <setjmp.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

#include "log.h"

static int indent = 2;
static int delta = 2;
static char *sp = " ";

#if INTERFACE
#ifndef YYMALLOCARGTYPE
#define YYMALLOCARGTYPE size_t
#endif
#endif
#line 45 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
#include "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.h"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#if INTERFACE
#define PACKAGE                         1
#define VERSION                         2
#define DESCRIPTION                     3
#define DIRECTORY                       4
#define VNAME                           5
#define FLAGS                           6
#define WORD                            7
#define WORDS                           8
#define REQUIRES                        9
#define PPX_RUNTIME_DEPS               10
#define WARNING                        11
#define ERROR                          12
#define DQ                             13
#define EQ                             14
#define PLUSEQ                         15
#define LPAREN                         16
#define RPAREN                         17
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 28
#define YYACTIONTYPE unsigned char
#if INTERFACE
#define ParseTOKENTYPE  union meta_token* 
#endif
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
  struct obzl_meta_package* yy1;
  UT_array* yy2;
  struct obzl_meta_property* yy5;
  struct obzl_meta_flag* yy10;
  obzl_meta_values* yy19;
  obzl_meta_entries* yy21;
  struct obzl_meta_entry* yy26;
  enum obzl_meta_opcode_e yy56;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#if INTERFACE
#define ParseARG_SDECL  struct obzl_meta_package *the_root_pkg;
#define ParseARG_PDECL , struct obzl_meta_package *the_root_pkg
#define ParseARG_PARAM ,the_root_pkg
#define ParseARG_FETCH  struct obzl_meta_package *the_root_pkg=yypParser->the_root_pkg;
#define ParseARG_STORE yypParser->the_root_pkg=the_root_pkg;
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#endif
#define YYNSTATE             17
#define YYNRULE              16
#define YYNRULE_WITH_ACTION  16
#define YYNTOKEN             18
#define YY_MAX_SHIFT         16
#define YY_MIN_SHIFTREDUCE   32
#define YY_MAX_SHIFTREDUCE   47
#define YY_ERROR_ACTION      48
#define YY_ACCEPT_ACTION     49
#define YY_NO_ACTION         50
#define YY_MIN_REDUCE        51
#define YY_MAX_REDUCE        66
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (51)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */    53,   16,   51,   16,   37,    6,   37,    6,    9,    5,
 /*    10 */     4,    5,    4,   52,    3,   12,    8,   38,   49,   16,
 /*    20 */    15,   11,   37,    6,   46,   47,   14,    5,    4,   46,
 /*    30 */    47,   52,    2,   62,   46,   47,   44,   45,   46,   47,
 /*    40 */    35,   36,    7,   61,   60,   10,   59,   13,   58,   50,
 /*    50 */     1,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    20,    1,    0,    1,    4,    5,    4,    5,   19,    9,
 /*    10 */    10,    9,   10,   20,   21,   19,    6,   17,   25,    1,
 /*    20 */    19,    6,    4,    5,   14,   15,    6,    9,   10,   14,
 /*    30 */    15,   20,   21,   27,   14,   15,    7,    8,   14,   15,
 /*    40 */     7,    8,   19,   27,   27,   19,   27,   19,   27,   28,
 /*    50 */    16,   28,   28,   28,   28,   28,   28,   28,   28,   28,
 /*    60 */    28,   28,   28,   28,   28,   28,   28,   28,   28,
};
#define YY_SHIFT_COUNT    (16)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (34)
static const unsigned char yy_shift_ofst[] = {
 /*     0 */    18,   18,    0,    2,   10,   15,   20,   29,   24,   29,
 /*    10 */    29,   24,   29,   29,   24,   33,   34,
};
#define YY_REDUCE_COUNT (14)
#define YY_REDUCE_MIN   (-20)
#define YY_REDUCE_MAX   (28)
static const signed char yy_reduce_ofst[] = {
 /*     0 */    -7,   11,  -20,  -20,  -11,   -4,    1,    6,   23,   16,
 /*    10 */    17,   26,   19,   21,   28,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */    48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
 /*    10 */    48,   48,   48,   48,   48,   48,   48,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#ifndef NDEBUG
#include <stdio.h>
#include <assert.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "PACKAGE",
  /*    2 */ "VERSION",
  /*    3 */ "DESCRIPTION",
  /*    4 */ "DIRECTORY",
  /*    5 */ "VNAME",
  /*    6 */ "FLAGS",
  /*    7 */ "WORD",
  /*    8 */ "WORDS",
  /*    9 */ "REQUIRES",
  /*   10 */ "PPX_RUNTIME_DEPS",
  /*   11 */ "WARNING",
  /*   12 */ "ERROR",
  /*   13 */ "DQ",
  /*   14 */ "EQ",
  /*   15 */ "PLUSEQ",
  /*   16 */ "LPAREN",
  /*   17 */ "RPAREN",
  /*   18 */ "property",
  /*   19 */ "opcode",
  /*   20 */ "entry",
  /*   21 */ "entries",
  /*   22 */ "flag",
  /*   23 */ "flags",
  /*   24 */ "properties",
  /*   25 */ "package",
  /*   26 */ "packages",
  /*   27 */ "words",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "package ::= entries",
 /*   1 */ "entries ::= entry",
 /*   2 */ "entries ::= entries entry",
 /*   3 */ "entry ::= VNAME opcode WORD",
 /*   4 */ "entry ::= VNAME opcode WORDS",
 /*   5 */ "entry ::= DIRECTORY",
 /*   6 */ "entry ::= PACKAGE LPAREN entries RPAREN",
 /*   7 */ "entry ::= VNAME FLAGS opcode words",
 /*   8 */ "entry ::= REQUIRES opcode words",
 /*   9 */ "entry ::= REQUIRES FLAGS opcode words",
 /*  10 */ "entry ::= PPX_RUNTIME_DEPS opcode words",
 /*  11 */ "entry ::= PPX_RUNTIME_DEPS FLAGS opcode words",
 /*  12 */ "words ::= WORD",
 /*  13 */ "words ::= WORDS",
 /*  14 */ "opcode ::= EQ",
 /*  15 */ "opcode ::= PLUSEQ",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
    case 18: /* property */
{
#line 60 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"

    log_trace("freeing property");
    /* free((yypminor->yy5)); */

#line 562 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
}
      break;
    case 20: /* entry */
{
#line 68 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"

    log_trace("freeing entry");
    free((yypminor->yy26));

#line 572 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
}
      break;
    case 21: /* entries */
{
#line 74 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"

    log_trace("freeing entries");
    utarray_free((yypminor->yy21)->list);

#line 582 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
}
      break;
    case 22: /* flag */
{
#line 80 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"

    log_trace("freeing flag %s", (yypminor->yy10)->s);
    free((yypminor->yy10));

#line 592 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
}
      break;
    case 23: /* flags */
{
#line 86 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"

    log_trace("freeing flags");
    utarray_free((yypminor->yy2));

#line 602 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
}
      break;
    case 24: /* properties */
{
#line 93 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"

    log_trace("freeing properties");
    /* free((yypminor->yy2)); */

#line 612 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
}
      break;
    case 25: /* package */
{
#line 99 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"

    log_trace("freeing package");
    /* free((yypminor->yy1)); */

#line 622 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
}
      break;
    case 26: /* packages */
{
#line 105 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"

    log_trace("freeing packages");
    /* free((yypminor->yy2)); */

#line 632 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
}
      break;
    case 27: /* words */
{
#line 112 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"

    log_trace("freeing words");
    utarray_free((yypminor->yy19)->list);

#line 642 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
}
      break;
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    25,  /* (0) package ::= entries */
    21,  /* (1) entries ::= entry */
    21,  /* (2) entries ::= entries entry */
    20,  /* (3) entry ::= VNAME opcode WORD */
    20,  /* (4) entry ::= VNAME opcode WORDS */
    20,  /* (5) entry ::= DIRECTORY */
    20,  /* (6) entry ::= PACKAGE LPAREN entries RPAREN */
    20,  /* (7) entry ::= VNAME FLAGS opcode words */
    20,  /* (8) entry ::= REQUIRES opcode words */
    20,  /* (9) entry ::= REQUIRES FLAGS opcode words */
    20,  /* (10) entry ::= PPX_RUNTIME_DEPS opcode words */
    20,  /* (11) entry ::= PPX_RUNTIME_DEPS FLAGS opcode words */
    27,  /* (12) words ::= WORD */
    27,  /* (13) words ::= WORDS */
    19,  /* (14) opcode ::= EQ */
    19,  /* (15) opcode ::= PLUSEQ */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) package ::= entries */
   -1,  /* (1) entries ::= entry */
   -2,  /* (2) entries ::= entries entry */
   -3,  /* (3) entry ::= VNAME opcode WORD */
   -3,  /* (4) entry ::= VNAME opcode WORDS */
   -1,  /* (5) entry ::= DIRECTORY */
   -4,  /* (6) entry ::= PACKAGE LPAREN entries RPAREN */
   -4,  /* (7) entry ::= VNAME FLAGS opcode words */
   -3,  /* (8) entry ::= REQUIRES opcode words */
   -4,  /* (9) entry ::= REQUIRES FLAGS opcode words */
   -3,  /* (10) entry ::= PPX_RUNTIME_DEPS opcode words */
   -4,  /* (11) entry ::= PPX_RUNTIME_DEPS FLAGS opcode words */
   -1,  /* (12) words ::= WORD */
   -1,  /* (13) words ::= WORDS */
   -1,  /* (14) opcode ::= EQ */
   -1,  /* (15) opcode ::= PLUSEQ */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;
  assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
#ifndef NDEBUG
  if( yyTraceFILE ){
    yysize = yyRuleInfoNRhs[yyruleno];
    if( yysize ){
      fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
        yyTracePrompt,
        yyruleno, yyRuleName[yyruleno],
        yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
        yymsp[yysize].stateno);
    }else{
      fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
        yyTracePrompt, yyruleno, yyRuleName[yyruleno],
        yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
    }
  }
#endif /* NDEBUG */

  /* Check that the stack is large enough to grow by a single entry
  ** if the RHS of the rule is empty.  This ensures that there is room
  ** enough on the stack to push the LHS value */
  if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
    if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
      yypParser->yyhwm++;
      assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack));
    }
#endif
#if YYSTACKDEPTH>0 
    if( yypParser->yytos>=yypParser->yystackEnd ){
      yyStackOverflow(yypParser);
      /* The call to yyStackOverflow() above pops the stack until it is
      ** empty, causing the main parser loop to exit.  So the return value
      ** is never used and does not matter. */
      return 0;
    }
#else
    if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
      if( yyGrowStack(yypParser) ){
        yyStackOverflow(yypParser);
        /* The call to yyStackOverflow() above pops the stack until it is
        ** empty, causing the main parser loop to exit.  So the return value
        ** is never used and does not matter. */
        return 0;
      }
      yymsp = yypParser->yytos;
    }
#endif
  }

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* package ::= entries */
#line 141 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>package ::= entries");
    log_trace("  package (yylhsminor.yy1)");
    log_trace("  entries (yymsp[0].minor.yy21)");
    dump_entries(0, yymsp[0].minor.yy21);
    log_trace("xxxxxxxxxxxxxxxx");
#endif
    /* yylhsminor.yy1 = (struct obzl_meta_package*)calloc(sizeof(struct obzl_meta_package), 1); */
    /* yylhsminor.yy1->entries = yymsp[0].minor.yy21; */
    the_root_pkg->entries = yymsp[0].minor.yy21;
    /* *the_root_pkg = yylhsminor.yy1; */
    yylhsminor.yy1 = the_root_pkg;
#if DEBUG_TRACE
    log_debug("DUMPING yylhsminor.yy1");
    dump_package(0, yylhsminor.yy1);
    log_debug("DUMPED yylhsminor.yy1");
#endif
}
#line 1080 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
  yymsp[0].minor.yy1 = yylhsminor.yy1;
        break;
      case 1: /* entries ::= entry */
#line 162 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>entries ::= entry");
    log_trace("%*sentries lhs (yylhsminor.yy21)", indent, sp);
    log_trace("%*sentry (yymsp[0].minor.yy26)", indent, sp);
    dump_entry(indent, yymsp[0].minor.yy26);
#endif
    /* lhs yylhsminor.yy21: lemon only allocates the type (a ptr); we must allocate/init the struct */
    yylhsminor.yy21 = (obzl_meta_entries*)calloc(sizeof(struct obzl_meta_entries), 1);
    utarray_new(yylhsminor.yy21->list, &entry_icd);
    utarray_push_back(yylhsminor.yy21->list, yymsp[0].minor.yy26);
#if DEBUG_TRACE
    dump_entries(indent, yylhsminor.yy21);
#endif
}
#line 1101 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
  yymsp[0].minor.yy21 = yylhsminor.yy21;
        break;
      case 2: /* entries ::= entries entry */
#line 180 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>entries ::= entries entry");
    log_trace("%*sentries lhs(yylhsminor.yy21)", indent, sp); //, obzl_meta_entries_count(yylhsminor.yy21));
    log_trace("%*sentries rhs(yymsp[-1].minor.yy21)", indent, sp); //, obzl_meta_entries_count(yymsp[-1].minor.yy21));
    dump_entries(delta+indent, yymsp[-1].minor.yy21);
    log_trace("%*sentry (yymsp[0].minor.yy26)", indent, sp); //, obzl_meta_entries_count(yymsp[-1].minor.yy21));
    dump_entry(delta+indent, yymsp[0].minor.yy26);
#endif

    normalize_entries(yymsp[-1].minor.yy21, yymsp[0].minor.yy26);
    yylhsminor.yy21 = yymsp[-1].minor.yy21;
    /* log_trace("after normalization"); */
#if DEBUG_TRACE
    /* log_trace("//entries ::= entries entry DONE"); */
    /* dump_entries(delta+indent, yylhsminor.yy21); */
#endif
}
#line 1125 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
  yymsp[-1].minor.yy21 = yylhsminor.yy21;
        break;
      case 3: /* entry ::= VNAME opcode WORD */
#line 202 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>entry ::= VNAME opcode WORD");
    log_trace("  entry (yylhsminor.yy26)");
    log_trace("  var (yymsp[-2].minor.yy0): %s", yymsp[-2].minor.yy0->s);
    log_trace("  opcode (yymsp[-1].minor.yy56): %d", yymsp[-1].minor.yy56);
    /* if (yymsp[0].minor.yy0) */
    /*     log_trace("  WORD (yymsp[0].minor.yy0): %s", yymsp[0].minor.yy0->s); */
    /* else */
    /*     log_trace("  WORD (yymsp[0].minor.yy0): <empty>", yymsp[0].minor.yy0->s); */
#endif
    yylhsminor.yy26 = handle_simple_prop(yymsp[-2].minor.yy0, yymsp[-1].minor.yy56, yymsp[0].minor.yy0);
    /* dump_entry(indent, yylhsminor.yy26); */
}
#line 1145 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
  yymsp[-2].minor.yy26 = yylhsminor.yy26;
        break;
      case 4: /* entry ::= VNAME opcode WORDS */
#line 218 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>entry ::= VNAME opcode WORDS");
    log_trace("\tentry (yylhsminor.yy26)");
    log_trace("\tpword (yymsp[-2].minor.yy0): %s", yymsp[-2].minor.yy0->s);
    log_trace("\topcode (yymsp[-1].minor.yy56): %d", yymsp[-1].minor.yy56);
    log_trace("\tWORD (W): %s", yymsp[0].minor.yy0->s);
#endif
    yylhsminor.yy26 = handle_simple_prop(yymsp[-2].minor.yy0, yymsp[-1].minor.yy56, yymsp[0].minor.yy0);
    /* dump_entry(delta, yylhsminor.yy26); */
}
#line 1162 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
  yymsp[-2].minor.yy26 = yylhsminor.yy26;
        break;
      case 5: /* entry ::= DIRECTORY */
#line 263 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>entry ::= DIRECTORY");
#endif
    yylhsminor.yy26 = handle_primitive_prop(DIRECTORY, yymsp[0].minor.yy0);
#if DEBUG_TRACE
    /* dump_entry(0, yylhsminor.yy26); */
#endif
}
#line 1177 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
  yymsp[0].minor.yy26 = yylhsminor.yy26;
        break;
      case 6: /* entry ::= PACKAGE LPAREN entries RPAREN */
#line 305 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>entry ::= PACKAGE LPAREN entries RPAREN");
    log_trace("  entry lhs(yylhsminor.yy26): %p", yylhsminor.yy26);
    log_trace("  entries rhs(yymsp[-1].minor.yy21)");
    log_trace("  the_root_pkg->name: %s", the_root_pkg->name);
    log_trace("  the_root_pkg->directory: %s", the_root_pkg->directory);
    log_trace("  the_root_pkg->metafile: %s", the_root_pkg->metafile);
    /* entries: utarray of struct obzl_meta_entry */
    dump_entries(indent, yymsp[-1].minor.yy21);
#endif
    /* yylhsminor.yy26 = handle_primitive_prop(PACKAGE, yymsp[-3].minor.yy0); */
    struct obzl_meta_package *new_package = (struct obzl_meta_package*)calloc(sizeof(struct obzl_meta_package), 1);
    new_package->name = yymsp[-3].minor.yy0->s;
    /* directory will be filled in during post-processing, from parent and directory prop. */
    /* new_package->directory = the_root_pkg->directory; */
    new_package->metafile = the_root_pkg->metafile; // THE_METAFILE;
    new_package->entries = yymsp[-1].minor.yy21;
    /* dump_package(indent, new_package); */

    yylhsminor.yy26 = (struct obzl_meta_entry*)calloc(sizeof(struct obzl_meta_entry), 1);
    yylhsminor.yy26->type = OMP_PACKAGE;
    yylhsminor.yy26->package = new_package;
    /* dump_entry(0, yylhsminor.yy26); */
}
#line 1208 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
  yymsp[-3].minor.yy26 = yylhsminor.yy26;
        break;
      case 7: /* entry ::= VNAME FLAGS opcode words */
#line 334 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>entry ::= VNAME FLAGS opcode words");
    log_trace("\tentry (yylhsminor.yy26)");
    log_trace("\tvarname (yymsp[-3].minor.yy0): %s", yymsp[-3].minor.yy0->s);
    log_trace("\tflags (FLAGS): %s", yymsp[-2].minor.yy0->s);
    /* dump_flags(FLAGS); */
    log_trace("\topcode (yymsp[-1].minor.yy56): %d", yymsp[-1].minor.yy56);
    log_trace("\twords (yymsp[0].minor.yy19)"); //: %s", W->s);
#endif

    /* new_prop->name = strdup(yymsp[-3].minor.yy0->s); */
    struct obzl_meta_property *new_prop= obzl_meta_property_new(strdup(yymsp[-3].minor.yy0->s));
    /* struct obzl_meta_property *new_prop= (struct obzl_meta_property*)malloc(sizeof(struct obzl_meta_property)); */
    /* utarray_new(new_prop->settings->list, &obzl_meta_setting_icd); */

    struct obzl_meta_setting *new_setting = obzl_meta_setting_new(yymsp[-2].minor.yy0->s, yymsp[-1].minor.yy56, yymsp[0].minor.yy19);
    utarray_push_back(new_prop->settings->list, new_setting);

    /* new_prop->setting = (struct obzl_meta_setting*)malloc(sizeof(struct obzl_meta_setting)); */
    /* new_prop->setting->flags = obzl_meta_flags_new_tokenized(FLAGS->s); */
    /* new_prop->setting->opcode = yymsp[-1].minor.yy56; */
    /* new_prop->setting->values = yymsp[0].minor.yy19; */

    struct obzl_meta_entry *new_entry= (struct obzl_meta_entry*)malloc(sizeof(struct obzl_meta_entry));
    new_entry->type = OMP_PROPERTY;
    new_entry->property = new_prop;

    yylhsminor.yy26 = new_entry;
    /* log_trace("output:"); */
    /* dump_entry(0, yylhsminor.yy26); */
    /* dump_values(yymsp[0].minor.yy19); */
    /* yylhsminor.yy26 = handle_compound_prop(P, FLAGS, yymsp[-1].minor.yy56, yymsp[0].minor.yy19); */
    /* dump_entry(0, yylhsminor.yy26); */
}
#line 1249 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
  yymsp[-3].minor.yy26 = yylhsminor.yy26;
        break;
      case 8: /* entry ::= REQUIRES opcode words */
#line 374 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>entry ::= REQUIRES opcode words");
    log_trace("%*sentry (yylhsminor.yy26)", indent, sp);
    log_trace("%*sopcode (yymsp[-1].minor.yy56): %d", indent, sp, yymsp[-1].minor.yy56);
    log_trace("%*swords (yymsp[0].minor.yy19)", indent, sp);
#endif

    /* validate_requires_args(yymsp[0].minor.yy19); */

    /* /\* yylhsminor.yy26 = handle_primitive_prop(yymsp[-2].minor.yy0, yymsp[-1].minor.yy56, yymsp[0].minor.yy19); *\/ */
    /* struct obzl_meta_property *new_prop= (struct obzl_meta_property*)malloc(sizeof(struct obzl_meta_property)); */
    /* /\* new_prop->name = strdup(token_names[token_type]); // "version"); *\/ */
    /* new_prop->name = strdup("requires"); */
    /* /\* new_prop->setting = (struct obzl_meta_setting*)malloc(sizeof(struct obzl_meta_setting)); *\/ */
    /* /\* new_prop->setting->flags = NULL; *\/ */
    /* /\* new_prop->setting->opcode = yymsp[-1].minor.yy56; *\/ */
    /* /\* new_prop->setting->values  = yymsp[0].minor.yy19; *\/ */
    /* utarray_new(new_prop->settings->list, &obzl_meta_setting_icd); */
    /* struct obzl_meta_setting *new_setting = obzl_meta_setting_new(NULL, yymsp[-1].minor.yy56, yymsp[0].minor.yy19); */
    /* utarray_push_back(new_prop->settings->list, new_setting); */

    struct obzl_meta_property *new_prop= obzl_meta_property_new(strdup("requires"));

    struct obzl_meta_setting *new_setting = obzl_meta_setting_new(NULL, yymsp[-1].minor.yy56, yymsp[0].minor.yy19);
    utarray_push_back(new_prop->settings->list, new_setting);

    struct obzl_meta_entry *new_entry= (struct obzl_meta_entry*)malloc(sizeof(struct obzl_meta_entry));
    new_entry->type = OMP_PROPERTY;
    new_entry->property = new_prop;

    yylhsminor.yy26 = new_entry;
    /* dump_entry(delta+indent, yylhsminor.yy26); */
}
#line 1289 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
  yymsp[-2].minor.yy26 = yylhsminor.yy26;
        break;
      case 9: /* entry ::= REQUIRES FLAGS opcode words */
#line 410 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>entry ::= REQUIRES LPAREN flag RPAREN opcode words");
    log_trace("%*sentry (yymsp[-3].minor.yy26)", indent, sp);
    log_trace("%*sflags (yymsp[-2].minor.yy0): %s", indent, sp, yymsp[-2].minor.yy0->s);
    /* dump_flags(yymsp[-2].minor.yy0); */
    log_trace("%*sopcode (yymsp[-1].minor.yy56): %d", indent, sp, yymsp[-1].minor.yy56);
    log_trace("%*swords (yymsp[0].minor.yy19)", indent, sp);
    /* dump_values(yymsp[0].minor.yy19); */
#endif
    /* yymsp[-3].minor.yy26 = handle_requires_prop(yymsp[-2].minor.yy0, yymsp[-1].minor.yy56, yymsp[0].minor.yy19); */

    /* validate_requires_args(yymsp[0].minor.yy19); */

    /* struct obzl_meta_property *new_prop= (struct obzl_meta_property*)malloc(sizeof(struct obzl_meta_property)); */
    /* new_prop->name = strdup("requires"); */
    struct obzl_meta_property *new_prop= obzl_meta_property_new(strdup("requires"));

    struct obzl_meta_setting *new_setting = obzl_meta_setting_new(yymsp[-2].minor.yy0->s, yymsp[-1].minor.yy56, yymsp[0].minor.yy19);
    utarray_push_back(new_prop->settings->list, new_setting);

    /* utarray_new(new_prop->settings->list, &obzl_meta_setting_icd); */
    /* struct obzl_meta_setting *new_setting = obzl_meta_setting_new(yymsp[-2].minor.yy0->s, yymsp[-1].minor.yy56, yymsp[0].minor.yy19); */
    /* utarray_push_back(new_prop->settings->list, new_setting); */

    /* new_prop->setting = (struct obzl_meta_setting*)malloc(sizeof(struct obzl_meta_setting)); */
    /* new_prop->setting->flags = obzl_meta_flags_new_tokenized(yymsp[-2].minor.yy0->s); */
    /* new_prop->setting->opcode = yymsp[-1].minor.yy56; */
    /* new_prop->setting->values = yymsp[0].minor.yy19; */

    struct obzl_meta_entry *new_entry= (struct obzl_meta_entry*)malloc(sizeof(struct obzl_meta_entry));
    new_entry->type = OMP_PROPERTY;
    new_entry->property = new_prop;

    yymsp[-3].minor.yy26 = new_entry;
    /* log_trace("output:"); */
    /* dump_entry(0, yymsp[-3].minor.yy26); */
}
#line 1333 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
        break;
      case 10: /* entry ::= PPX_RUNTIME_DEPS opcode words */
#line 454 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>entry ::= PPX_RUNTIME_DEPS opcode words");
    log_trace("%*sentry (yymsp[-2].minor.yy26)", indent, sp);
    log_trace("%*sopcode (yymsp[-1].minor.yy56): %d", indent, sp, yymsp[-1].minor.yy56);
    log_trace("%*swords (yymsp[0].minor.yy19)", indent, sp);
#endif

    struct obzl_meta_property *new_prop= obzl_meta_property_new(strdup("ppx_runtime_deps"));

    struct obzl_meta_setting *new_setting = obzl_meta_setting_new(NULL, yymsp[-1].minor.yy56, yymsp[0].minor.yy19);
    utarray_push_back(new_prop->settings->list, new_setting);

    struct obzl_meta_entry *new_entry= (struct obzl_meta_entry*)malloc(sizeof(struct obzl_meta_entry));
    new_entry->type = OMP_PROPERTY;
    new_entry->property = new_prop;

    yymsp[-2].minor.yy26 = new_entry;
    /* dump_entry(delta+indent, yymsp[-2].minor.yy26); */
}
#line 1358 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
        break;
      case 11: /* entry ::= PPX_RUNTIME_DEPS FLAGS opcode words */
#line 476 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>entry ::= PPX_RUNTIME_DEPS LPAREN flag RPAREN opcode words");
    log_trace("%*sentry (yymsp[-3].minor.yy26)", indent, sp);
    log_trace("%*sflags (yymsp[-2].minor.yy0): %s", indent, sp, yymsp[-2].minor.yy0->s);
    /* dump_flags(yymsp[-2].minor.yy0); */
    log_trace("%*sopcode (yymsp[-1].minor.yy56): %d", indent, sp, yymsp[-1].minor.yy56);
    log_trace("%*swords (yymsp[0].minor.yy19)", indent, sp);
    /* dump_values(yymsp[0].minor.yy19); */
#endif
    struct obzl_meta_property *new_prop= obzl_meta_property_new(strdup("ppx_runtime_deps"));

    struct obzl_meta_setting *new_setting = obzl_meta_setting_new(yymsp[-2].minor.yy0->s, yymsp[-1].minor.yy56, yymsp[0].minor.yy19);
    utarray_push_back(new_prop->settings->list, new_setting);

    struct obzl_meta_entry *new_entry= (struct obzl_meta_entry*)malloc(sizeof(struct obzl_meta_entry));
    new_entry->type = OMP_PROPERTY;
    new_entry->property = new_prop;

    yymsp[-3].minor.yy26 = new_entry;
    /* log_trace("output:"); */
    /* dump_entry(0, yymsp[-3].minor.yy26); */
}
#line 1386 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
        break;
      case 12: /* words ::= WORD */
#line 508 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>words ::= WORD");
    log_trace("\twords lhs(yylhsminor.yy19)");
    if (yymsp[0].minor.yy0->s == NULL)
        log_trace("\tWORD (yymsp[0].minor.yy0): NULL");
    else
        log_trace("\tWORD (yymsp[0].minor.yy0): %s", yymsp[0].minor.yy0->s);
#endif
    /* UT_array *new_values = obzl_meta_values_new_copy(yymsp[0].minor.yy0->s); */
    obzl_meta_values *new_values = obzl_meta_values_new(yymsp[0].minor.yy0->s);
    /* dump_values(indent, new_values); */
    yylhsminor.yy19 = new_values;
}
#line 1405 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
  yymsp[0].minor.yy19 = yylhsminor.yy19;
        break;
      case 13: /* words ::= WORDS */
#line 524 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>words ::= WORDS");
    log_trace("\twords lhs(yylhsminor.yy19)");
    log_trace("\tWORDS (yymsp[0].minor.yy0): %s", yymsp[0].minor.yy0->s);
#endif
    obzl_meta_values *new_values = obzl_meta_values_new_tokenized(yymsp[0].minor.yy0->s);
    /* dump_values(indent, new_values); */
    yylhsminor.yy19 = new_values;
    /* utarray_new(new_values, &ut_str_icd); */
    /* utarray_push_back(new_values, &(VALTOK->s)); */
    /* new_prop->setting->values = new_values; */
}
#line 1424 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
  yymsp[0].minor.yy19 = yylhsminor.yy19;
        break;
      case 14: /* opcode ::= EQ */
#line 546 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>opcode ::= EQ");
    log_trace("\topcode lhs(yylhsminor.yy56)");
    log_trace("\tEQ (yymsp[0].minor.yy0)");
#endif
    yylhsminor.yy56 = OP_SET;
}
#line 1438 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
  yymsp[0].minor.yy56 = yylhsminor.yy56;
        break;
      case 15: /* opcode ::= PLUSEQ */
#line 556 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"
{
#if DEBUG_TRACE
    log_trace("\n");
    log_trace(">>opcode(yylhsminor.yy56) ::= PLUSEQ(yymsp[0].minor.yy0)");
#endif
    yylhsminor.yy56 = OP_UPDATE;
}
#line 1450 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
  yymsp[0].minor.yy56 = yylhsminor.yy56;
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 118 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"

    log_trace("**************** Syntax error! ****************");
    exit(EXIT_FAILURE);
#line 1517 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
#line 123 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.y"

    log_trace("Parsing complete");
#line 1546 "/private/var/tmp/_bazel_gar/2cf1b1cbc37d32d28204189d83247676/external/obazl_tools_opam/bootstrap/metaparser.c"
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  do{
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      yyact = yy_reduce(yypParser,yyact-YY_MIN_REDUCE,yymajor,
                        yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos >= yypParser->yystack
            && (yyact = yy_find_reduce_action(
                        yypParser->yytos->stateno,
                        YYERRORSYMBOL)) > YY_MAX_SHIFTREDUCE
        ){
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos < yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }while( yypParser->yytos>yypParser->yystack );
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
