.Dd April 9, 2022
.Dt @COPAM 1
.Sh NAME
.Nm @copam//<subcmd>
.Sh SYNOPSIS
.Nm $ bazel run @copam//<subcmd>
.Op --
.Op Ar options
.Sh DESCRIPTION
The @opam workspace contains tools for managing OBazl
.Em coswitches ,
which serve to integrate OPAM resources into the Bazel ecosystem.
.Sh CONFIGURATION
In your
.Em WORKSPACE.bazel
file:
.Bd -literal -offset indent
git_repository(
    name = "opam",
    remote = "https://github.com/obazl/tools_opam",
    branch = "obazl2",
)

load("@opam//:WORKSPACE.bzl", "opam_fetch_repos")
opam_fetch_repos()

load("@rules_foreign_cc//foreign_cc:repositories.bzl",
     "rules_foreign_cc_dependencies")
rules_foreign_cc_dependencies()

load("//.obazl.d:BOOTSTRAP.bzl", copam_bootstrap="bootstrap")
copam_bootstrap()

register_toolchains("@ocaml//toolchains:ocaml_macos")
register_toolchains("@ocaml//toolchains:ocaml_linux")
.Ed
.Sh EXAMPLES
.Sh SEE ALSO
.Xr copam_here
.Xr copam_coswitch
.Sh AUTHORS
.An Gregg Reynolds
