.Dd April 9, 2022
.Dt @OPAM-HERE-REFRESH 1
.Os OBazl User Manual
.Sh NAME
.Nm @opam//here:refresh
.Nd Refresh here coswitch
.Sh SYNOPSIS
.Sy @opam//here:refresh
.Op Fl h
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl h
Display this help screen.
.El
.Sh DESCRIPTION
Refreshes project-local
.Sy here
coswitch.
.Sh EXAMPLES
.Sh SEE ALSO
To display the manpage for a command:
.Bd -literal -offset indent
$ bazel run @opam//coswitch:list -- -h
.Ed
.Pp
.Xr @opam//coswitch:show
.Xr @opam//coswitch:refresh
.Xr here
.Sh AUTHORS
.An Gregg Reynolds
