.Dd April 9, 2022
.Dt @OPAM-LOCAL-IMPORT 1
.Os OBazl User Manual
.Sh NAME
.Nm @opam//local:import
.Nd Import OPAM local-switch
.Sh SYNOPSIS
.Sy @opam//local:import
.Op Fl h
.Sh DESCRIPTION
Imports OPAM local-switch.
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl V
Pass option
.Ql --verbose
to OPAM commands.
.It Fl v
Verbose output
.It Fl h
Display this help screen.
.El
.Sh SEE ALSO
.Xr @opam//local:list
.Xr @opam//local:export
.Xr @opam//local/opam:init
.Xr @opam//local/opam:install
.Xr @opam//local/opam:remove
.Xr local
.Sh AUTHORS
.An Gregg Reynolds
