.Dd April 9, 2022
.Dt @OPAM-COSWITCH-LIST 1
.Os OBazl User Manual
.Sh NAME
.Nm @opam//coswitch:list
.Nd List effective coswitch.
.Sh SYNOPSIS
.Sy @opam//coswitch:list
[
.Fl -
.Op Fl s Ar coswitch
.Op Fl h
.Sy ]
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl s Ar coswitch
List
.Em coswitch .
.It Fl h
Display this help screen.
.El
.Sh DESCRIPTION
Display info about coswitch.  If option
.Fl s
not passed, list current effective coswitch.
.Sh EXAMPLES
.Sh SEE ALSO
To display the manpage for a command:
.Bd -literal -offset indent
$ bazel run @opam//coswitch:list -- -h
.Ed
.Pp
.Xr @opam//coswitch:show
.Xr @opam//coswitch:refresh
.Xr here
.Sh AUTHORS
.An Gregg Reynolds
