.Dd April 9, 2022
.Dt @OPAM-SHARED-REFRESH 1
.Os OBazl User Manual
.Sh NAME
.Nm @opam//shared:refresh
.Nd Refresh shared (XDG) coswitch from OPAM switch
.Sh SYNOPSIS
.Sy @opam//shared:refresh
.Fl -
.Ar switch
.Op Fl h
.Sh OPTIONS
.Bl -tag -width -indent
.It Ar switch
Refresh shared coswitch from switch
.Em switch .
.It Fl h
Display this help screen.
.El
.Sh DESCRIPTION
Refreshes shared (XDG) coswitch. Writes coswitch to
.Pa $XDG_DATA_HOME/obazl/opam
(default:
.Pa $HOME/.local/share/obazl/opam
).
.Sh EXAMPLES
.Bd -literal -offset indent
$ bazel run @opam//shared:refresh -- 4.14.0
.Ed
.Sh SEE ALSO
To display the manpage for a command:
.Bd -literal -offset indent
$ bazel run @opam//coswitch:list -- -h
.Ed
.Pp
.Xr @opam//coswitch:show
.Xr @opam//coswitch:refresh
.Xr here
.Sh AUTHORS
.An Gregg Reynolds
