.Dd April 9, 2022
.Dt @OPAM-HERE-OPAM-INSTALL 1
.Os OBazl User Manual
.Sh NAME
.Nm @opam//here/opam:install
.Nd Install OPAM package into
.Sy here
switch.
.Sh SYNOPSIS
.Sy @opam//here/opam:install
[
.Fl -
.Op Ar package ...
.Op Fl h
.Sy ]
.Sh DESCRIPTION
Installs packages into here switch.  Multiple packages arguments supported.
.Sh OPTIONS
.Bl -tag -width -indent
.It Ar package
Install
.Ar package
in the
.Pa .opam
switch.
.It Fl h
Display this help screen.
.El
.Sh SEE ALSO
.Xr @opam//here:create
.Xr @opam//here/opam:init
.Xr @opam//here/opam:remove
.Xr here
.Sh AUTHORS
.An Gregg Reynolds
