.Dd April 9, 2022
.Dt @OPAM-LOCAL-INIT 1
.Os OBazl User Manual
.Sh NAME
.Nm @opam//local:init
.Nd Initialize OPAM
.Sy local
switch.
.Sh SYNOPSIS
.Sy @opam//local:init
[
.Fl -
.Op Ar compiler_version
.Op Fl h
.Sy ]
.Sh DESCRIPTION
Initializes OPAM
.Sy local
switch at
.Pa $(PWD)/_opam .
.Sh OPTIONS
.Bl -tag -width -indent
.Op Ar compiler_version
Compiler version to install.
.It Fl h
Display this help screen.
.El
.Sh SEE ALSO
.Xr @opam//local
.Sh AUTHORS
.An Gregg Reynolds
