.Dd April 9, 2022
.Dt @OPAM-HERE-OPAM-REINIT 1
.Os OBazl User Manual
.Sh NAME
.Nm @opam//here/opam:reinit
.Nd Reinitialize here
.Sy here
switch and coswitch.
.Sh SYNOPSIS
.Sy @opam//here/opam:reinit
.Op Fl h
.Sh DESCRIPTION
Reinitializes OPAM
.Sy here switch
at
.Pa $(PWD)/.opam
and refreshes OBazl
.Sy here coswitch.
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl h
Display this help screen.
.El
.Sh SEE ALSO
.Xr @opam//here:create
.Xr @opam//here/opam:init
.Xr @opam//here/opam:install
.Xr @opam//here/opam:remove
.Xr here
.Sh AUTHORS
.An Gregg Reynolds
