.Dd April 9, 2022
.Dt @OPAM-HERE-CREATE 1
.Os OBazl User Manual
.Sh NAME
.Nm @opam//here:create
.Nd Create OBazl here-switch and coswitch
.Sh SYNOPSIS
.Sy @opam//here:create
[
.Fl -
.Op Fl c Ar version
.Op Fl h
.Sy ]
.Sh DESCRIPTION
Initializes OPAM installation at $(PWD)/.opam and creates switch
named
.Ql here .
With no option, installs the compiler version of the OPAM switch currently active.
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl c Ar version
Install compiler version
.Ar version
in the
.Pa .opam
switch.
.Ar version
must be one of the version strings listed by the OPAM command
.Bd -literal -offset indent
$ opam switch list-available
.Ed
.It Fl s Ar switch
Use the configuration of OPAM switch
.Ar switch
to create the
.Em here
coswitch.
.It Fl D
Dry-run.  Prints but does not execute commands that mutate the file system.
.It Fl V
Pass option
.Ql --verbose
to OPAM commands.
.It Fl v
Verbose output
.It Fl h
Display this help screen.
.El
.Sh SEE ALSO
.Xr @opam//here:clean
.Xr @opam//here:create
.Xr @opam//here:export
.Xr @opam//here:expunge
.Xr @opam//here:import
.Xr @opam//here:list
.Xr @opam//here:refresh
.Xr @opam//here:reinit
.Xr @opam//here:set
.Pp
.Xr @opam//here/opam:init
.Xr @opam//here/opam:install
.Xr @opam//here/opam:remove
.Sh AUTHORS
.An Gregg Reynolds
