.Dd April 9, 2022
.Dt @OPAM-HERE-OPAM-INIT 1
.Os OBazl User Manual
.Sh NAME
.Nm @opam//here/opam:init
.Nd Initialize
.Sy here
switch.
.Sh SYNOPSIS
.Sy @opam//here/opam:init
[
.Fl -
.Op Fl h
.Sy ]
.Sh DESCRIPTION
Initializes OPAM
.Sy here
switch at
.Pa $(PWD)/.opam .
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl h
Display this help screen.
.El
.Sh SEE ALSO
.Xr @opam//here:create
.Xr @opam//here/opam:install
.Xr @opam//here/opam:remove
.Xr here
.Sh AUTHORS
.An Gregg Reynolds
