.Dd April 9, 2022
.Dt @OPAM-HERE-IMPORT 1
.Os OBazl User Manual
.Sh NAME
.Nm @opam//here:import
.Nd Import OPAM here-switch
.Sh SYNOPSIS
.Sy @opam//here:import
.Op Fl h
.Sh DESCRIPTION
Imports OPAM here-switch.
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl V
Pass option
.Ql --verbose
to OPAM commands.
.It Fl v
Verbose output
.It Fl h
Display this help screen.
.El
.Sh SEE ALSO
.Xr @opam//here:list
.Xr @opam//here:export
.Xr @opam//here/opam:init
.Xr @opam//here/opam:install
.Xr @opam//here/opam:remove
.Xr here
.Sh AUTHORS
.An Gregg Reynolds
